name: riverpod_structure
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  skeletonizer: ^1.4.3
  flutter_svg: ^2.0.17
  flutter_gen: ^5.6.0
  hive_flutter: ^1.1.0
  share_plus: ^10.1.4
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  internet_connection_checker: ^3.0.1
  pinput: ^5.0.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  device_info_plus: ^11.3.3
  path_provider: ^2.1.4
  socket_io_client: ^2.0.3+1

  firebase_core: ^3.12.1
  auto_size_text: ^3.0.0
  firebase_messaging: ^15.2.4
  flutter_localizations:
    sdk: flutter
  picker_pro_max_ultra: ^2.0.10


  #  firebase_auth: ^5.3.0
  flutter_local_notifications: ^17.2.3
  #  flutter_file_compressor: ^0.0.7


  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  dropdown_button2: ^2.3.9
  file_picker: ^9.2.2
  card_swiper: ^3.0.1
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.12.2
  geolocator: ^14.0.1
  package_info_plus: ^8.3.0
  flutter_widget_from_html_core: ^0.16.0
  url_launcher: ^6.3.1
  amazon_cognito_identity_dart_2: ^3.8.1
  crypto: ^3.0.6
  path: ^1.9.1
  app_links: ^6.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.6.0
  hive_generator: ^2.0.1
  retrofit_generator: ^8.2.0




flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true
  # Assets
  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/map/


  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700


flutter_gen:
  output: lib/gen/
  integrations:
    image: true
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    outputs:
      directory_path_enabled: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
